### ISSUE TITLE
adcolony ad would not call onReward() method while a GC happened

### ISSUE THREAD

**Issue by zfnian** [googleads/googleads-mobile-android-mediation#431] opened 2022-11-07 13:30 UTC
1. The sdk version we use is below:
    implementation 'com.google.android.gms:play-services-ads:21.0.0'
    implementation 'com.google.ads.mediation:adcolony:4.8.0.0'
2. After we call RewardedAd.load() to request reward Ad success, then call show() method, now Adcolony will call
"override fun onAdShowedFullScreenContent()、override fun onAdImpression() to Admob, but not call override fun onUserEarnedReward() to Admob.
3. After we debug, we find: As the AdColonyRewardedRenderer is a weak reference, it would be recycled for some reasons, when it is recycled, method getListener() return null, so will not call onReward() method to Admob, please help to check this issue, thanks very much!
![image](https://user-images.githubusercontent.com/14959222/200322595-8a3647c0-867b-40e8-82b2-1d1bfa558243.png)
![image](https://user-images.githubusercontent.com/14959222/200322645-3a49c6ba-5ddd-4b74-8e56-4bd07b5c3d14.png)

**Comment by joshuajplagonera** [comment] 2023-02-02 19:07
Hi @zfnian 

Are you dropping the reference to the ad once its shown? We have been able to reproduce under these conditions but believe that's an implementation issue.
The adapter maintains a weak reference since the Google Mobile Ads SDK maintains a strong reference to the adapter as long as the app maintains a strong reference to the ad object. By dropping the ad object, the Google ad object and its strong reference to the adapter will be garbage collected.

**Comment by joshuajplagonera** [comment] 2023-02-13 22:16
Closing for now.
Please re-open a new issue if you are still experiencing this issue with the latest adapters.

**Closed by joshuajplagonera** 2023-02-13 22:16 UTC
