### ISSUE TITLE
Error calling adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter

### ISSUE THREAD

**Issue by KimiChiu** [googleads/googleads-mobile-android-mediation#333] opened 2021-05-14 09:49 UTC
It is showing `Error calling adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter` every time after calling `MobileAds.initialize`.
I tried to use other versions but still not working.

implementation 'com.google.ads.mediation:facebook:6.4.0.0'
implementation 'com.google.android.gms:play-services-ads:20.1.0'

**Comment by ShanePhelan** [comment] 2021-06-15 12:25
I'm seeing this issue too but on older adapter versions:

implementation 'com.google.ads.mediation:facebook:5.11.0.0'
implementation 'com.google.android.gms:play-services-ads:18.3.0'

**Comment by adbourdages** [comment] 2021-07-02 19:21
I am seeing the same problem.

Setup
- Unity 2019.4.21f
- Admob Unity SDK 6.1.0
- Facebook Unity Mediation Plugin 3.3.0

Dependencies
- com.google.ads.mediation:facebook:6.4.0.0
- com.google.android.gms:play-services-ads:20.0.0

Resolved libraries
- com.facebook.android.audience-network-sdk-6.5.0
- com.google.ads.mediation.facebook-6.5.0.0
- com.google.android.gms.play-services-ads-20.2.0

Logcat
```
I/Unity: [AdmobManager] com.google.android.gms.ads.MobileAds is Ready: 
I/Unity: [AdmobManager] com.google.ads.mediation.facebook.FacebookMediationAdapter is Ready: 
[...]
W/Ads: Not retrying to fetch app settings
[...]
E/Ads: Error calling adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter
```

Nothing else relevant in the logcat, unfortunately.

**Comment by ericleich** [comment] 2021-07-21 15:57
Are you all trying to implement Facebook bidding specifically, and is this 100% reproducible on your end?

That error message being thrown by the Google Mobile Ads Android SDK appears to only happen in code paths for bidding, and only when catching an error. Would need to be able to reproduce to unpack why such an error might be thrown.

**Comment by ShanePhelan** [comment] 2021-07-28 11:56
@ericleich yes that's correct, I'm using Facebook bidding. I'll see if I can reproduce it in a skeleton app

**Comment by adbourdages** [comment] 2021-08-11 17:35
I'm circling back on this issue as a user is experiencing unexplained crashes on RewardedAd.ShowAd that may (or may not) be related to this.

Interestingly, the issue is not 100% reproducible. Some app launches will give the error, some won't (same builds and device, app opened/closed just a few minutes apart).

I am not sure what you mean by "Facebook bidding" exactly. The facebook ad unit is using open bidding, but my understanding is that it is still admob driving the bidding. The mediation group has a very basic setup.

**Comment by Nyankoo** [comment] 2022-06-19 23:44
Anyone solved this? Still seeing this error.

**Comment by cap1-0** [comment] 2022-11-08 05:39
my app was running fine yesterday today morning i am started getting this error i am using latest version

**Comment by large** [comment] 2023-04-13 20:20
Did any of you solve this? In my flutter app I see the same:
> I/Ads     (23540): This request is sent from a test device.
> E/Ads     (23540): Error calling adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter

No error at all, with "no sdk signal found" (since it never loaded).

**Comment by ShanePhelan** [comment] 2023-04-14 09:32
Hi, @large No, unfortunately not. I've not been able to get any adverts returned by Facebook via Google Admob mediation. 

I now see a "No ad config" error when requesting an ad from Facebook

**Comment by large** [comment] 2023-04-14 10:38
Thanks for the feedback, such a waste of time trying to get this to work.

I am giving up now, Meta has non existing customer relations for devs and I cannot get the debugger running the adapter either. Hopefully some more brighter than me have deeper knowledge to finding the reason.

**Comment by AlexUrrutia** [comment] 2023-04-17 19:32
Same here

`Error calling adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter`

But it shows as initialized and found in Ad inspector...
what's going on?

**Comment by ericleich** [comment] 2023-04-20 22:33
Signal collection has a 1 second timeout. When debugging this, we identified that a signal timeout results in this error message.

Back in September 2022, Meta made some improvements that dramatically improved their signal collection time on the first request of a session. Prior to that, their first call would timeout a non-trivial amount of the time. I'm a bit surprised to hear this coming up again after last September.

To rule out timeout issues, can you please confirm:

1. Whether these logs are roughly 1 second apart from each other when you reproduce:
  ```
  I/Ads (23540): This request is sent from a test device.
  E/Ads (23540): Error calling adapter: com.google.ads.mediation.facebook.FacebookMediationAdapter
  ```

2. If you were to make a throwaway call to Meta's `BidderTokenProvider.getBidderToken(context)` method prior to initializing the Google Mobile Ads SDK, does this error go away?

**Comment by ShanePhelan** [comment] 2023-04-21 07:09
Hi @ericleich thanks for the context.

I'll try your suggestion but I've never seen any code like that before in any of the documentation for using Meta with Google admob meditation. Can you point me to any relevant documentation? Perhaps I'm not implementing bidding correctly.

According to Google, you just need to include the FB ads sdk and the admob FB adapter. There's no reference to any additional code?

**Comment by ericleich** [comment] 2023-04-21 19:37
Your understanding is correct that you shouldn't have to write that code in production. That line of code is what [the adapter is doing](https://github.com/googleads/googleads-mobile-android-mediation/blob/9dd249edee75db2288a0ae130c664555ea52526e/ThirdPartyAdapters/meta/meta/src/main/java/com/google/ads/mediation/facebook/FacebookMediationAdapter.java#L238) when it attempts to collect signals. Last September, we found that the first call was slow and could timeout, but subsequent requests were cached. Meta then made some server-side change that made the first call fast - likely they are doing any caching as part of their initialization.

My questions above were an attempt to tease out whether you are getting a signal collection timeout issue, or something else is going wrong (since they'll both hit the same generic error). If you aren't comfortable adding that code to a test project, having timestamps on the above logs would help understand if they're ~1 second apart which matches the signal timeout.

Another possible issue, do you follow the guidance at https://developers.google.com/admob/android/mediate#initialize_the_mobile_ads_sdk to wait for the Google Mobile Ads SDK to finish initialization prior to loading ads. If you DON'T wait for this to finish, then Meta's SDK wouldn't get a chance to initialize, [this line of code](https://github.com/googleads/googleads-mobile-android-mediation/blob/9dd249edee75db2288a0ae130c664555ea52526e/ThirdPartyAdapters/meta/meta/src/main/java/com/google/ads/mediation/facebook/FacebookMediationAdapter.java#L238) is the first time it knows to try and get their signals, and it experiences the same issue pre-September 2022 where it may last more than 1 second on the first ad request of each app session. This is my best guess as to what might be happening, please confirm your implementation.

**Comment by Nyankoo** [comment] 2023-04-21 19:48
@ericleich I'm facing the same issue with Meta, but with the Unity SDK for Android. I'm just wanting to add that this issue still happens when waiting until the SDK finished initialization before loading ads. As the Unity SDK uses the Android SDK under the hood, I assume that info could be helpful to some extend.

**Comment by ShanePhelan** [comment] 2023-05-17 13:30
@ericleich Thanks for the explanation. I've added that line and I am no longer seeing the "error calling adapter"

However, I am unable to get any ads returned by Meta. 

Via the mobile ads inspector I see a "No SDK signal found" for test banner ad requests and "No user consent provided" for interstitial ad requests

**Comment by joshh-devrel** [comment] 2023-11-03 16:48
Closed as this isn't reproducible on our end.

Please use the [latest Meta Android adapter version](https://developers.google.com/admob/android/mediation/meta#meta-audience-network-android-mediation-adapter-changelog).

**Closed by joshh-devrel** 2023-11-03 16:48 UTC

**Comment by Akshay340-mob** [comment] 2024-08-07 11:13
I had the issue of timeout while testing but It finally got worked but installing the facebook app and login on it while testing.
[https://developers.facebook.com/docs/audience-network/setting-up/testing/platform#test-mobile-apps](url)
