### ISSUE TITLE
NoClassDefFoundError - MoPub Banner

### ISSUE THREAD

**Issue by JustinTipton** [googleads/googleads-mobile-android-mediation#16] opened 2017-08-10 15:41 UTC
I'm seeing the following crash using the MoPub adapter, version 4.15.0

java.lang.NoClassDefFoundError: 
  at com.mopub.mobileads.dfp.adapters.MoPubAdapter$2.<clinit> (MoPubAdapter.java:182)
  at com.mopub.mobileads.dfp.adapters.MoPubAdapter$a.onBannerFailed (MoPubAdapter.java:312)
  at com.mopub.mobileads.MoPubView.a (MoPubView.java:252)
  at com.mopub.mobileads.AdViewController.b (AdViewController.java:507)
  at com.mopub.mobileads.AdViewController.a (AdViewController.java:177)
  at com.mopub.mobileads.AdViewController$1.onErrorResponse (AdViewController.java:125)
  at com.mopub.volley.Request.deliverError (Request.java:577)
  at com.mopub.volley.ExecutorDelivery$a.run (ExecutorDelivery.java:101)
  at android.os.Handler.handleCallback (Handler.java:836)

I am using Proguard, with the following.
-keepclassmembers class com.mopub.** { public *; }
-keep public class com.mopub.**
-keep public class com.mopub.mobileads.dfp.adapters.**

Here is a look at the java for the method after proguard.
public final void onBannerFailed(MoPubView paramMoPubView, MoPubErrorCode paramMoPubErrorCode)
    {
      switch (MoPubAdapter.2.b[paramMoPubErrorCode.ordinal()])
      {
      default: 
        this.b.onAdFailedToLoad(MoPubAdapter.this, 0);
        return;
      case 1: 
        this.b.onAdFailedToLoad(MoPubAdapter.this, 3);
        return;
      case 2: 
        this.b.onAdFailedToLoad(MoPubAdapter.this, 2);
        return;
      }
      this.b.onAdFailedToLoad(MoPubAdapter.this, 1);
    }

And lastly, here is the proguard mapping.
com.mopub.mobileads.dfp.adapters.MoPubAdapter$2 -> com.mopub.mobileads.dfp.adapters.MoPubAdapter$2:
    int[] $SwitchMap$com$mopub$nativeads$NativeErrorCode -> a
    int[] $SwitchMap$com$mopub$mobileads$MoPubErrorCode -> b
    182:312:void <clinit>() -> <clinit>

I have no clue why this is happening. I think I've done everything appropriately, but this anonymous inner class is crashing.

**Comment by sbagadi** [comment] 2017-08-11 18:37
I was not able to reproduce the issue. I was able to load and show MoPub banner ads while using Proguard. I didn't add any additional Proguard `keep` rules. The Google Mobile Ads SDK already has the following rule which should make sure that the mediation adapters are not removed by Proguard:

```
-keep class * implements com.google.ads.mediation.MediationAdapter {
  public *;
}
```

Could you please provide a sample app that can reproduces the issue.

**Comment by sbagadi** [comment] 2017-09-26 20:37
Closing the issue as obsolete. Please reopen the issue if otherwise.

**Closed by sbagadi** 2017-09-26 20:37 UTC
